# Generated by Django 2.1.4 on 2019-01-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelRecommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.IntegerField(unique=True)),
                ('spot_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserToCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelRecommend.CityInfo')),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='usertocity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelRecommend.UserInfo'),
        ),
    ]
