# Generated by Django 2.1.4 on 2019-01-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelRecommend', '0002_auto_20190111_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cityinfo',
            name='intro',
            field=models.CharField(default='简介完善中……', max_length=300),
        ),
        migrations.AddField(
            model_name='img',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelRecommend.CityInfo'),
        ),
    ]
